name: Ping Supabase and Keep Alive

on:
  schedule:
    - cron: '0 0 * * 0,4'
  workflow_dispatch:

jobs:
  ping_and_commit:
    environment: production
    runs-on: ubuntu-latest
    # Permission to push code back to the repo
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          # Use a variable to ensure the string is built correctly
          FULL_URL="${SUPABASE_URL}/rest/v1/gostations?select=id&limit=1"
          curl -X GET "$FULL_URL" \
          -H "apikey: ${SUPABASE_KEY}" \
          -H "Authorization: Bearer ${SUPABASE_KEY}"

      - name: Keep Workflow Active
        run: |
          date > heartbeat.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add heartbeat.txt
          git commit -m "Heartbeat: $(date)" || echo "No changes to commit"
          git push
